apiVersion: v1
kind: Service
metadata:
  name: mindx-webapp-service
  labels:
    app: mindx-webapp
spec:
  type: ClusterIP
  selector:
    app: mindx-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
